### ISSUE TITLE
No way to close Quickword without focusing on another app

### ISSUE THREAD

**Issue by kdwk** [hezral/quickword#13]
If an app is not open in the background, and I don't want to open a new app, there is no apparent way to close Quickword (clicking on Wingpanel also works but yeah). I propose that Quickword close itself if the user clicks anywhere other than the Quickword window.

**Comment by hezral** [comment]
That's actually how the window manager works. without a window to switch focus to, quickword can't unfocus and trigger to quit. 

I'll have to think about this

**Comment by hezral** [comment]
You could enable the close button in the options and manually quit it from there
