### ISSUE TITLE
The app shouldn't require the user to install the wordnet package manually 

### ISSUE THREAD

**Issue by hanaral** [hezral/quickword#2]
It's quite tedious, and also means that the app won't even launch without creating the necessary folder and installing the files to it via python.

**Comment by hezral** [comment]
thanks, are you referring to the manual python setup? currently the deb takes care of the dependencies. I will add it in the instruction and maybe a simple script for manual install.

**Comment by hanaral** [comment]
The deb package didn't do the setup for me, I'd recommend you retest this with a clean environment.

**Comment by hezral** [comment]
Found the issue and fixed https://github.com/hezral/quickword/commit/056582a75ed58bc4115181345f519a2a3f3d89fe 
Thanks for catching it.
