### ISSUE TITLE
Round corner radius should match elementary 6 style

### ISSUE THREAD

**Issue by hanaral** [hezral/quickword#3]
Right now the window's rounded corners radius seems to be in the elementary 5 style. It's not really necessary but it would be nice.

**Comment by hezral** [comment]
Yes, it will be updated to elementary 6 once its released. Right now i can't even submit to AppCenter due to repository not showing up in the AppCenter dashboard https://github.com/elementary/houston/issues/799

I'm going to close this for now since its planned for future release.
