### ISSUE TITLE
Change required for AppCenter: OARS data

### ISSUE THREAD

**Issue by cassidyjames** [hezral/quickword#6]
Thanks for submitting your app to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Since your app depends on an external web service, its `social-info` value **must** be set to `mild` or higher, depending on the data that is sent. You can always ensure your OARS data is correct by using the [official OARS generator](https://hughsie.github.io/oars/).

https://github.com/hezral/quickword/blob/cb40af6e68b3d2fd05d07d4f15cfbf051750a4aa/data/com.github.hezral.quickword.appdata.xml#L66

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). As always, if you have any questions you can reply here.

**Comment by hezral** [comment]
Thanks Cassidy. I've updated it in a216681 and resubmit
